openapi: 3.0.3
info:
  title: Personal Finance Tracker API
  version: 1.0.0
  description: API для приложения учета личных финансов
servers:
  - url: http://localhost:8080
    description: Локальный сервер
  - url: http://103.76.52.13:8080
    description: Удаленный тестовый сервер
paths:
  /api/registration:
    post:
      summary: Регистрация нового пользователя
      description: Создает аккаунт и возвращает JWT-токен.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        '201':
          description: Пользователь успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
        '400':
          description: Ошибка валидации входящих полей (длина пароля, формат email, некорректное имя).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                error: "Validation Failed"
                message: "password: User password length must be between 10 and 60 characters"
                status: 400
                timestamp: "2026-05-29 12:00:00"
        '409':
          description: Конфликт уникальности. Пользователь с таким email уже зарегистрирован в системе.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                error: "Conflict"
                message: "User with email user@example.com already exists"
                status: 409
                timestamp: "2026-05-29 12:00:00"

  /api/login:
    post:
      summary: Аутентификация пользователя (Вход в личный кабинет)
      description: Проверяет учетные данные и возвращает JWT-токен.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Успешный вход
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JwtResponse'
        '404':
          description: Пользователь не найден (не зарегистрирован)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                error: "Resource Not Found"
                message: "User with email = user2@example.com was not found"
                status: 404
                timestamp: "2026-05-29 12:00:00"
        '403':
          description: Ошибка ввода пароля
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                error: "Forbidden"
                message: "/api/login"
                status: 403
                timestamp: "2026-05-29 12:00:00"

  /api/v1/accounts:
    get:
      summary: Получить список счетов текущего авторизованного пользователя
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Успешный ответ со списком счетов пользователя
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AccountInfoDto'
        '404':
          description: Пользователь не авторизован (неверный или отсутствующий JWT)
            или профиль текущего пользователя не найден в системе

    post:
      summary: Создание нового счета
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountCreateRequest'
      responses:
        '201':
          description: Счет успешно создан для текущего пользователя (определяется по JWT).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountInfoDto'
        '400':
          description: Ошибка валидации входящих полей (неверный формат валюты или некорректное имя счета).
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                error: "Validation Failed"
                message: "currency: must be one of RUB, EUR, USD"
                status: 400
                timestamp: "2026-05-29 12:00:00"
        '404':
          description: Пользователь не авторизован (неверный или отсутствующий JWT)
            или профиль текущего пользователя не найден в системе

  /api/v1/accounts/{accountId}:
    put:
      summary: Обновить настройки счета
      security:
        - BearerAuth: [ ]
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountUpdateRequest'
      responses:
        '200':
          description: Счет успешно обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountInfoDto'
        '400':
          description: Неверный формат данных
        '404':
          description: Пользователь не авторизован (неверный или отсутствующий JWT)
            или счет текущего пользователя не найден в системе

    delete:
      summary: Удалить счет
      security:
        - BearerAuth: [ ]
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '204':
          description: Счет успешно удален (No Content)
        '404':
          description: Пользователь не авторизован (неверный или отсутствующий JWT)
            или счет текущего пользователя не найден в системе

  /api/v1/accounts/{accountId}/transaction:
    get:
      summary: Получить историю транзакций по конкретному счету
      security:
        - BearerAuth: [ ]
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
        - name: page
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
        - name: size
          in: query
          schema:
            type: integer
            minimum: 1
            default: 20
      responses:
        '200':
          description: Успешный ответ с пагинацией
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagedTransactionResponse'

  /api/v1/categories:
    get:
      summary: Получить список всех категорий
      responses:
        '200':
          description: Список категорий получен
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CategoryInfoDto'
    post:
      summary: Создать новую категорию (Доступно только ADMIN)
      security:
        - BearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryCreateRequest'
      responses:
        '201':
          description: Категория создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryInfoDto'
        '400':
          description: Ошибка валидации имени категории
        '403':
          description: Доступ запрещен (не ADMIN)

  /api/v1/categories/{categoryId}:
    delete:
      summary: Удалить категорию (Доступно только ADMIN)
      security:
        - BearerAuth: [ ]
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '204':
          description: Категория удалена
        '403':
          description: Доступ запрещен

  /api/v1/transactions:
    post:
      summary: Добавить новую транзакцию с поддержкой идемпотентности
      security:
        - BearerAuth: []
      parameters:
        - name: X-Idempotency-Key
          in: header
          required: true
          schema:
            type: string
            format: uuid
            example: "123e4567-e89b-12d3-a456-426614174000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionRequest'
      responses:
        '201':
          description: Транзакция успешно добавлена (или возвращена из кэша идемпотентности)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionInfoDto'
        '400':
          description: Ошибка бизнес-логики или валидации при создании транзакции.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              examples:
                InsufficientFunds:
                  summary: Нехватка средств (овердрафт запрещен)
                  value:
                    error: "Insufficient Funds"
                    message: "Недостаточно средств на счете. Баланс: 0.00, Попытка списания: 5000.0"
                    status: 400
                    timestamp: "2026-06-20 12:00:00"
                CurrencyMismatch:
                  summary: Несовпадение валюты операции и счёта
                  value:
                    error: "Currency Mismatch"
                    message: "Несовпадение валюты. Валюта счёта ID = 1 - RUB, валюта операции - USD"
                    status: 400
                    timestamp: "2026-05-29 12:00:00"
                ValidationFailed:
                  summary: Ошибка формата данных или отсутствие заголовка
                  value:
                    error: "Validation Failed"
                    message: "Idempotency key is missing / amount must be greater than 0"
                    status: 400
                    timestamp: "2026-05-29 12:00:00"
        '404':
          description: Указанный в теле запроса accountId не найден, либо этот счёт не принадлежит текущему пользователю.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                error: "Resource Not Found"
                message: "Счет не найден с id: 1"
                status: 404
                timestamp: "2026-05-29 12:00:00"
        '409':
          description: |
            Конфликт идемпотентности (Duplicate request). 
            Если для данного ключа в Redis уже существует запись ответа idempotency-key (хранится 12 часов),
            API автоматически вернет сохраненный успешный ответ (статус 201).
            
            Если ответа в кэше нет,
            система пытается установить распределенную блокировку idempotency-key на 180 секунд.
            
            Статус 409 возвращается в случае, если распределенная блокировка уже удерживается другим параллельным потоком.
            Это означает, что идентичный запрос прямо сейчас находится в процессе обработки базой данных.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
              example:
                error: "Idempotency key already in use"
                message: "Duplicate request in progress"
                status: 409
                timestamp: "2026-06-24T17:15:00.000Z"

  /api/v1/transactions/{transactionId}:
    put:
      summary: Изменить существующую транзакцию
      security:
        - BearerAuth: [ ]
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionUpdateRequest'
      responses:
        '200':
          description: Транзакция успешно обновлена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionInfoDto'
    delete:
      summary: Удалить транзакцию
      security:
        - BearerAuth: []
      parameters:
        - name: transactionId
          in: path
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
      responses:
        '204':
          description: Транзакция удалена

  /api/v1/reports/monthly:
    get:
      summary: Получить сводный отчет за месяц
      security:
        - BearerAuth: []
      parameters:
        - name: year
          in: query
          required: true
          schema:
            type: integer
            minimum: 2000
            maximum: 2100
            example: 2026
        - name: month
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 12
            example: 6
      responses:
        '200':
          description: Отчет успешно сгенерирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonthlyReportDto'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegistrationRequest:
      type: object
      required: [ email, password, firstName, timezone ]
      properties:
        email:
          type: string
          format: email
          minLength: 6
          maxLength: 60
          example: "user@example.com"
        password:
          type: string
          minLength: 10
          maxLength: 60
          example: "password1234567890"
        firstName:
          type: string
          minLength: 2
          maxLength: 30
          example: "Иван"

    LoginRequest:
      type: object
      required: [ email, password ]
      properties:
        email:
          type: string
          format: email
          example: "user@example.com"
        password:
          type: string
          example: "password1234567890"

    JwtResponse:
      type: object
      properties:
        token:
          type: string
          example: "eyJhbGciOiJIUzI1NiIs..."
        email:
          type: string
          example: "user@example.com"
        role:
          type: string
          example: "ROLE_USER"

    AccountCreateRequest:
      type: object
      required: [ name, currency, initialBalance, overdraftAllowed ]
      properties:
        name:
          type: string
          maxLength: 100
          example: "Инвестиционный счет"
        currency:
          type: string
          enum: [ RUB, EUR, USD ]
          example: "RUB"
        initialBalance:
          type: number
          format: decimal
          minimum: 0
          example: 5000.00
        overdraftAllowed:
          type: boolean
          example: false

    AccountUpdateRequest:
      type: object
      properties:
        name:
          type: string
          maxLength: 100
          example: "Новое название счета"
        overdraftAllowed:
          type: boolean
          example: true

    AccountInfoDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Зарплатная карта"
        currency:
          type: string
          enum: [ RUB, EUR, USD ]
          example: "RUB"
        balance:
          type: number
          format: decimal
          example: 150000.50
        overdraftAllowed:
          type: boolean

    CategoryCreateRequest:
      type: object
      required: [ name ]
      properties:
        name:
          type: string
          maxLength: 50
          example: "Продукты"

    CategoryInfoDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: "Продукты"

    CategoryExpenseDto:
      type: object
      properties:
        category:
          type: string
          example: "Супермаркеты"
        totalExpense:
          type: number
          format: decimal
          example: 25400.00

    MonthlyReportDto:
      type: object
      properties:
        totalIncome:
          type: number
          format: decimal
          example: 120000.00
        totalExpense:
          type: number
          format: decimal
          example: 45000.00
        balanceDifference:
          type: number
          format: decimal
          example: 75000.00
        expenseByCategory:
          type: array
          items:
            $ref: '#/components/schemas/CategoryExpenseDto'

    TransactionRequest:
      type: object
      required: [ accountId, type, amount, currency, categoryId, date ]
      properties:
        accountId:
          type: integer
          format: int64
          minimum: 1
          example: 1
        type:
          type: string
          enum: [ INCOME, EXPENSE ]
          example: "EXPENSE"
        amount:
          type: number
          format: decimal
          minimum: 0.01
          example: 1500.00
        currency:
          type: string
          enum: [ RUB, EUR, USD ]
          example: "RUB"
        categoryId:
          type: integer
          format: int64
          minimum: 1
          example: 2
        date:
          type: string
          format: date-time
          example: "2026-06-26T12:00:00Z"
        description:
          type: string
          maxLength: 300
          example: "Покупка продуктов"

    TransactionUpdateRequest:
      type: object
      properties:
        amount:
          type: number
          format: decimal
          minimum: 0.01
          example: 1800.00
        type:
          type: string
          enum: [ INCOME, EXPENSE ]
        categoryId:
          type: integer
          format: int64
          minimum: 1
        date:
          type: string
          format: date-time
          example: "2026-06-26T12:00:00Z"
        description:
          type: string
          maxLength: 300

    TransactionInfoDto:
      type: object
      properties:
        transactionId:
          type: integer
          format: int64
          example: 105
        accountId:
          type: integer
          format: int64
          example: 1
        type:
          type: string
          enum: [ INCOME, EXPENSE ]
        amount:
          type: number
          format: decimal
          example: 1500.00
        category:
          type: string
          example: "Продукты"
        date:
          type: string
          format: date-time
          example: "2026-06-26T12:00:00Z"
        description:
          type: string
          example: "Покупка продуктов"
        accountBalance:
          type: number
          format: decimal
          example: 98500.00

    PagedTransactionResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/TransactionInfoDto'
        page:
          type: integer
          example: 0
        size:
          type: integer
          example: 20
        totalElements:
          type: integer
          format: int64
          example: 42
        totalPages:
          type: integer
          example: 3

    ApiError:
      type: object
      required: [ error, message, status, timestamp ]
      properties:
        error:
          type: string
        message:
          type: string
        status:
          type: integer
        timestamp:
          type: string
          format: date-time
